# Generated by Django 3.2.8 on 2021-11-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=30)),
                ('birthDate', models.DateTimeField(auto_now_add=True)),
                ('userEmail', models.EmailField(max_length=254)),
                ('userPassword', models.CharField(max_length=30)),
                ('userPermissions', models.CharField(choices=[('user', 'user'), ('premium', 'premium'), ('superuser', 'superuser')], max_length=30)),
                ('userstatus', models.BooleanField()),
                ('bio', models.TextField(default='404')),
                ('country', models.CharField(default='unknown', max_length=25)),
                ('pointes', models.IntegerField(default=0)),
            ],
        ),
    ]
