# Generated by Django 3.2.8 on 2021-11-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_birthdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birthDate',
        ),
        migrations.AddField(
            model_name='user',
            name='c',
            field=models.CharField(default='test', max_length=30),
        ),
    ]
