# Generated by Django 3.2.8 on 2021-11-07 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20211107_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthDate',
            field=models.DateField(default=datetime.datetime(2021, 11, 7, 18, 41, 12, 402714)),
        ),
        migrations.AlterField(
            model_name='user',
            name='pic',
            field=models.ImageField(default='default.jpg', upload_to='userPic'),
        ),
    ]
