# Generated by Django 3.2.8 on 2021-11-07 16:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20211107_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='genre',
            field=models.CharField(default=' ', max_length=30),
        ),
        migrations.AddField(
            model_name='image',
            name='imageDate',
            field=models.DateField(default=datetime.datetime(2021, 11, 7, 18, 55, 26, 693959)),
        ),
        migrations.AddField(
            model_name='image',
            name='imageTitle',
            field=models.CharField(default='unknown', max_length=60),
        ),
        migrations.AddField(
            model_name='image',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='s',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthDate',
            field=models.DateField(default=datetime.datetime(2021, 11, 7, 18, 55, 26, 693959)),
        ),
    ]
