# Generated by Django 3.2.8 on 2021-11-07 16:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20211107_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='s',
        ),
        migrations.AlterField(
            model_name='image',
            name='imageDate',
            field=models.DateField(default=datetime.datetime(2021, 11, 7, 18, 57, 15, 781360)),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthDate',
            field=models.DateField(default=datetime.datetime(2021, 11, 7, 18, 57, 15, 781360)),
        ),
    ]
