# Generated by Django 3.2.8 on 2021-11-07 18:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20211107_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='genre',
            field=models.CharField(choices=[('Natural', 'Natural'), ('Cars', 'Cars'), ('4K', '4K'), ('Anime', 'Anime')], max_length=30),
        ),
        migrations.AlterField(
            model_name='image',
            name='imageDate',
            field=models.DateField(default=datetime.datetime(2021, 11, 7, 20, 40, 40, 615477)),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthDate',
            field=models.DateField(default=datetime.datetime(2021, 11, 7, 20, 40, 40, 615477)),
        ),
    ]
