# Generated by Django 3.2.8 on 2021-11-07 18:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20211107_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='imageDate',
            field=models.DateField(default=datetime.datetime(2021, 11, 7, 20, 57, 11, 222018)),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthDate',
            field=models.DateField(default=datetime.datetime(2021, 11, 7, 20, 57, 11, 222018)),
        ),
        migrations.AlterField(
            model_name='user',
            name='json',
            field=models.JSONField(default=[{}]),
        ),
    ]
