# Generated by Django 3.2.8 on 2021-11-09 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20211109_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='imageDate',
            field=models.DateField(default=datetime.datetime(2021, 11, 9, 14, 48, 15, 661657)),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 9, 14, 48, 15, 660658)),
        ),
        migrations.AlterField(
            model_name='user',
            name='userstatus',
            field=models.BooleanField(null=True),
        ),
    ]
