# Generated by Django 3.2.8 on 2021-11-09 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20211109_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='createdDate',
        ),
        migrations.AlterField(
            model_name='image',
            name='imageDate',
            field=models.DateField(default=datetime.datetime(2021, 11, 9, 14, 57, 12, 781629)),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthDate',
            field=models.DateField(default=datetime.datetime(2021, 11, 9, 14, 57, 12, 780629)),
        ),
    ]
