# Generated by Django 3.2.8 on 2021-11-12 22:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20211112_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='json',
            new_name='favorite',
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.JSONField(default=[{}]),
        ),
        migrations.AlterField(
            model_name='image',
            name='imageDate',
            field=models.DateField(default=datetime.datetime(2021, 11, 13, 0, 50, 0, 96178)),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthDate',
            field=models.DateField(default=datetime.datetime(2021, 11, 13, 0, 50, 0, 94181)),
        ),
        migrations.AlterField(
            model_name='user',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 13, 0, 50, 0, 95180)),
        ),
        migrations.AlterField(
            model_name='user',
            name='userPermissions',
            field=models.CharField(choices=[('user', 'user'), ('premium', 'premium'), ('superuser', 'superuser')], default='user', max_length=30),
        ),
    ]
