# Generated by Django 3.2.8 on 2021-11-12 22:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20211113_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='imageDate',
            field=models.DateField(default=datetime.datetime(2021, 11, 13, 0, 53, 11, 154781)),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthDate',
            field=models.DateField(default=datetime.datetime(2021, 11, 13, 0, 53, 11, 152782)),
        ),
        migrations.AlterField(
            model_name='user',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 13, 0, 53, 11, 153782)),
        ),
        migrations.AlterField(
            model_name='user',
            name='userstatus',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
