# Generated by Django 3.2.8 on 2021-11-12 23:00

import datetime
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20211113_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country1',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='imageDate',
            field=models.DateField(default=datetime.datetime(2021, 11, 13, 1, 0, 48, 695130)),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthDate',
            field=models.DateField(default=datetime.datetime(2021, 11, 13, 1, 0, 48, 691134)),
        ),
        migrations.AlterField(
            model_name='user',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 13, 1, 0, 48, 694131)),
        ),
    ]
