# Generated by Django 3.2.8 on 2021-11-13 11:55

import datetime
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20211113_1212'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='image',
            managers=[
                ('map', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='genre',
        ),
        migrations.AddField(
            model_name='image',
            name='imageDesc',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='image',
            name='tags',
            field=models.JSONField(default=[{}]),
        ),
        migrations.AlterField(
            model_name='image',
            name='imageDate',
            field=models.DateField(default=datetime.datetime(2021, 11, 13, 13, 55, 31, 615029)),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 13, 13, 55, 31, 614030)),
        ),
        migrations.AlterField(
            model_name='user',
            name='userPassword',
            field=models.CharField(max_length=180),
        ),
    ]
