# Generated by Django 3.2.8 on 2021-11-13 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_auto_20211113_1357'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='image',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='imageDate',
            field=models.DateField(default=datetime.datetime(2021, 11, 13, 14, 0, 43, 234903)),
        ),
        migrations.AlterField(
            model_name='user',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 13, 14, 0, 43, 233904)),
        ),
    ]
