# Generated by Django 3.2.8 on 2021-11-13 12:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_auto_20211113_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='peruser',
            name='pus',
            field=models.ManyToManyField(to='app.Image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='imageDate',
            field=models.DateField(default=datetime.datetime(2021, 11, 13, 14, 9, 51, 996729)),
        ),
        migrations.AlterField(
            model_name='user',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 13, 14, 9, 51, 995731)),
        ),
    ]
