# Generated by Django 3.2.8 on 2021-11-14 20:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_auto_20211114_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='user1',
        ),
        migrations.AddField(
            model_name='chat',
            name='users',
            field=models.JSONField(default=[{}]),
        ),
        migrations.AlterField(
            model_name='image',
            name='imageDate',
            field=models.DateField(default=datetime.datetime(2021, 11, 14, 22, 8, 7, 60811)),
        ),
        migrations.AlterField(
            model_name='user',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 14, 22, 8, 7, 59814)),
        ),
    ]
