# Generated by Django 3.2.8 on 2021-11-16 09:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_auto_20211116_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='users',
            field=models.JSONField(default=[{}]),
        ),
        migrations.AlterField(
            model_name='image',
            name='imageDate',
            field=models.DateField(default=datetime.datetime(2021, 11, 16, 11, 28, 55, 83433)),
        ),
        migrations.AlterField(
            model_name='user',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 16, 11, 28, 55, 81434)),
        ),
    ]
