# Generated by Django 3.2.8 on 2021-11-16 10:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_auto_20211116_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chats',
            field=models.JSONField(default=[{'id': '1'}]),
        ),
        migrations.AlterField(
            model_name='image',
            name='imageDate',
            field=models.DateField(default=datetime.datetime(2021, 11, 16, 12, 57, 54, 167633)),
        ),
        migrations.AlterField(
            model_name='user',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 16, 12, 57, 54, 165634)),
        ),
    ]
