# Generated by Django 3.2.8 on 2021-11-24 21:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_auto_20211117_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tagsLike',
            field=models.JSONField(default=[{}]),
        ),
        migrations.AlterField(
            model_name='chatimage',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='chatImages'),
        ),
        migrations.AlterField(
            model_name='image',
            name='imageDate',
            field=models.DateField(default=datetime.datetime(2021, 11, 24, 23, 15, 3, 138031)),
        ),
        migrations.AlterField(
            model_name='user',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 24, 23, 15, 3, 136032)),
        ),
    ]
