# Generated by Django 3.2.8 on 2021-11-27 22:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_auto_20211128_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='mas',
            field=models.ManyToManyField(to='app.Gener'),
        ),
        migrations.AlterField(
            model_name='image',
            name='imageDate',
            field=models.DateField(default=datetime.datetime(2021, 11, 28, 0, 35, 27, 114284)),
        ),
        migrations.AlterField(
            model_name='user',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 28, 0, 35, 27, 112284)),
        ),
    ]
