# Generated by Django 3.2.8 on 2021-11-27 22:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_auto_20211128_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='flow',
            field=models.ManyToManyField(related_name='_app_user_flow_+', to='app.User'),
        ),
        migrations.AlterField(
            model_name='image',
            name='imageDate',
            field=models.DateField(default=datetime.datetime(2021, 11, 28, 0, 41, 7, 648692)),
        ),
        migrations.AlterField(
            model_name='user',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 28, 0, 41, 7, 645694)),
        ),
    ]
