# Generated by Django 3.2.8 on 2021-11-27 22:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0069_auto_20211128_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='ss',
            field=models.ManyToManyField(to='app.Chat'),
        ),
        migrations.AlterField(
            model_name='image',
            name='imageDate',
            field=models.DateField(default=datetime.datetime(2021, 11, 28, 0, 58, 1, 350000)),
        ),
        migrations.AlterField(
            model_name='user',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 28, 0, 58, 1, 346003)),
        ),
    ]
