# Generated by Django 3.2.8 on 2021-11-27 23:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0070_auto_20211128_0058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='ss',
        ),
        migrations.RemoveField(
            model_name='user',
            name='favorite',
        ),
        migrations.RemoveField(
            model_name='user',
            name='flow',
        ),
        migrations.AlterField(
            model_name='image',
            name='imageDate',
            field=models.DateField(default=datetime.datetime(2021, 11, 28, 1, 0, 24, 341555)),
        ),
        migrations.RemoveField(
            model_name='user',
            name='chats',
        ),
        migrations.AddField(
            model_name='user',
            name='chats',
            field=models.ManyToManyField(to='app.Chat'),
        ),
        migrations.AlterField(
            model_name='user',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 28, 1, 0, 24, 336558)),
        ),
        migrations.RemoveField(
            model_name='user',
            name='following',
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(related_name='_app_user_following_+', to='app.User'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='tagsLike',
        ),
        migrations.AddField(
            model_name='user',
            name='tagsLike',
            field=models.ManyToManyField(to='app.Tag'),
        ),
    ]
