# Generated by Django 3.2.8 on 2021-11-28 22:13

import datetime
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0074_auto_20211129_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='imageDate',
            field=models.DateField(default=datetime.datetime(2021, 11, 29, 0, 13, 57, 600770)),
        ),
        migrations.AlterField(
            model_name='image',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='app.Tag'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='chats',
            field=models.ManyToManyField(blank=True, null=True, to='app.Chat'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 29, 0, 13, 57, 596773)),
        ),
        migrations.AlterField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(blank=True, null=True, related_name='_app_user_following_+', to='app.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tagsLike',
            field=models.ManyToManyField(blank=True, null=True, to='app.Tag'),
        ),
    ]
