# Generated by Django 3.2.8 on 2021-12-06 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0076_auto_20211129_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='in_OurPicks',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='imageDate',
            field=models.DateField(default=datetime.datetime(2021, 12, 6, 14, 17, 34, 260970)),
        ),
        migrations.AlterField(
            model_name='user',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 6, 14, 17, 34, 255973)),
        ),
    ]
