# Generated by Django 3.2.8 on 2021-12-06 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0077_auto_20211206_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='in_OurPicks',
            new_name='inOurPicks',
        ),
        migrations.AlterField(
            model_name='image',
            name='imageDate',
            field=models.DateField(default=datetime.datetime(2021, 12, 6, 14, 18, 14, 539409)),
        ),
        migrations.AlterField(
            model_name='user',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 6, 14, 18, 14, 534413)),
        ),
    ]
