# Generated by Django 3.2.8 on 2021-12-10 23:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0079_auto_20211211_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='imageDate',
            field=models.DateField(default=datetime.datetime(2021, 12, 11, 1, 19, 54, 43244)),
        ),
        migrations.AlterField(
            model_name='image',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 11, 1, 19, 54, 43244)),
        ),
    ]
